settings: &common
  site_title:      '中盛会员信息平台'
  admin_key:       'china'
  admin_account:   'admin'
  admin_password:  'admin'
  
development:
  <<: *common
test:
  <<: *common
production:
  <<: *common